### ISSUE TITLE
Make it smarter

### ISSUE THREAD

**Issue by shikaan** [plibither8/licensed#1]
Hello! 
I just came across the project, I have seen the demo and it looks okay. However, for me at least, the big deal when it's time to choose a license is actually... Chosing it :D

What I am saying is this: is there any plan to add questions to help users while picking the right license for their specific case? 

If this sounds okay, I am available to contribute

**Comment by plibither8** [comment]
Hey! This is a great idea for which I did have plans to implement it. I guess I just forgot to. In any case, a big thumbs up to this idea.

What I was thinking of doing was adding a "-q" flag to the command like: `licensed -q` to bring up a small questionnaire that will walk you through in choosing a license. How does it sound?

I am more than willing to accept contributions, so feel free to work on it, I'll help along :) 

Cheers

**Comment by shikaan** [comment]
Submitted a PR (#2) for this :)
