### ISSUE TITLE
why are you offering 3-clause bsd

### ISSUE THREAD

**Issue by StoneCypher** [plibither8/licensed#3]
is there ever any reason to prefer 3-clause over 2-clause?  all that does is enable you to be incompatible with the gpl, the world's most pointlessly difficult and ineffective license

**Comment by plibither8** [comment]
Hey! Thanks for taking time to open this issue. While I do understand your concerns, I think its best for the user to decide what is best for them. I do understand that the consequences of choosing a *poor* license are not clearly highlighted in the questionnaire, so if you could, please link any source explicitly mentioning the demerits of the BSD-3-Clause license. If I do think it's worth to put up a warning, or remove it completely, I will. Or you could open a PR for that ;)

Nevertheless, please send a link, I'd really like to look into this. Thanks again!

**Comment by StoneCypher** [comment]
a link to what?

the difference between the two-clause and the three-clause is that a comment requiring a mention of the regents of the state of california uc berkeley was removed

that requirement is in conflict with the gpl

the whole reason for that removal was to end the unnecessary conflict with the gpl

i am not aware of any circumstances under which the old one is preferred.  it's just to avoid gpl neckbearding.

**Comment by StoneCypher** [comment]
https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22)

**Comment by plibither8** [comment]
According to GNU's own docs, the Modified BSD (3-clause) and FreeBSD (2-clause) both are are GPL compatible licenses.

https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses
