### ISSUE TITLE
the gpl is a problem

### ISSUE THREAD

**Issue by StoneCypher** [plibither8/licensed#4]
if you're going to help people choose licenses, you should mention that the gpl has failed all the legal protections it was supposed to offer ("tivoization") and causes huge problems interacting with the rest of the world, to no benefit

consider removing it, or at the least hiding it behind a gargantuan warning.  the gpl is dying for a reason

**Comment by plibither8** [comment]
As replied in #3 I think it'll be great if you could link up any reliable source. Thanks :)

**Comment by StoneCypher** [comment]
a link for what

**Comment by plibither8** [comment]
How about we consider adding LGPL?
