### ISSUE TITLE
Artistic-2.0 Plz!

### ISSUE THREAD

**Issue by jessehattabaugh** [plibither8/licensed#5]
I don't know, maybe I'm the only one that likes to use this License, but if others respond to this issue I'll start a PR.

**Comment by plibither8** [comment]
Hey! I don't see any reason *why* we can't or shouldn't have this on our list. I was anyway planning to update the list with a lot more opensource licenses so this could be our start! Make a PR and I'll look into it. Make sure to add all information about the license for the questionnaire. I'd recommend to look at https://tldrlegal.com/license/artistic-license-2.0-(artistic)

Thanks!
